PAS: Onboard new infrastructure providers
paseo-network/paseo-rfcs pull request #30
Opened 2024-02-12 12:10 UTC by al3mart

This document describes the process infrastructure providers willing to contribute should follow.

2024-02-12 12:11 UTC, al3mart commented
We might want to describe the monitoring part of it. Let me know what are your thoughts.

2024-02-12 13:23 UTC, hbulgarini approved these changes
Perfect, i don't have any arguments at all.

2024-02-13 10:40 UTC, helloitsbirdo requested changes
Please make the updated changes in the comments

2024-02-13 10:40 UTC, helloitsbirdo commented on rfcs/onboard_infrastructure_providers.md
> +Different members of the Polkadot ecosystem have expressed interest to participate in this initiative. A selection criteria is necessary to don't compromise the network while allowing as many parties
Many individuals and companies that provide infrastructure in the Polkadot ecosystem have expressed interest to participate in Paseo. A selection criteria is necessary to ensure high standards which avoid compromises or downtime to the network, while allowing as many parties as possible.

2024-02-13 10:40 UTC, helloitsbirdo commented on rfcs/onboard_infrastructure_providers.md
> +This RFC talks about how different infrastructure providers can support Paseo network.
This RFC (PAS) discusses about how different infrastructure providers can join and contribute to the Paseo network.

2024-02-13 10:40 UTC, helloitsbirdo commented on rfcs/onboard_infrastructure_providers.md
> +Interested infrastructure providers (referred as _Contributor_ or _the contributor_ from here on) should open a PR in this repository and label is as `infra onboarding`.
Interested infrastructure providers (referred as _Contributor_ or _the contributor_ from here on) should open a PR in this repository and label it, `infra onboarding`.

2024-02-13 10:40 UTC, helloitsbirdo commented on rfcs/onboard_infrastructure_providers.md
> +The **election criteria** is:
The **selection criteria** is:

2024-02-13 10:40 UTC, helloitsbirdo commented on rfcs/onboard_infrastructure_providers.md
> +- Contributor is part of [Polkadot 1KV Programme](https://wiki.polkadot.network/docs/thousand-validators).
- Contributor is part of the [Polkadot 1KV Programme](https://wiki.polkadot.network/docs/thousand-validators).

2024-02-13 10:40 UTC, helloitsbirdo commented on rfcs/onboard_infrastructure_providers.md
> +It seems reasonable that being Paseo a community testnet not a single party has to make all the efforts of maintaining this platform. At the same time, moving away from a single operator should not c
A Paseo is a decentralised community testnet, we want to open the opportunity for validators in the ecosystem to contribute to the success and scaling of the network.

2024-02-13 17:18 UTC, helloitsbirdo approved these changes
lfg

2024-02-13 17:20 UTC, merged